version: '3.8'

services:
  db:
    image: mysql:8
    container_name: blog_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 10203252
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate_api
    restart: always
    ports:
      - "5000:5000"
    command: ["--load-only", "en,es,pt-BR"]
    environment:
      - "APP_LANGUAGES=en,es,pt-BR"

volumes:
  db_data:
